name: Deploy Boletins

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Adicionar Token de Acesso
        env:
          ACCESS_TOKEN: ${{ secrets.PUBLIC_PATH_REPO }}
        run: echo "Token carregado!"

      - name: Publicar Alterações
        run: |
          git add .
          git commit -m "📄 Atualização automática dos boletins"
          git push https://x-access-token:${{ secrets.PUBLIC_PATH_REPO }}@github.com/tharlesjcp/iprc-boletins-publico.git main
